### ISSUE TITLE
Install fails on Node 7

### ISSUE THREAD

**Issue by dignifiedquire** [adzerk/node-lru-native#9]
- OS: MacOS 10.12.2
- Node: v7.2.1
- npm: 4.0.1

Log:

```
> lru-native@0.4.0 install /Users/dignifiedquire/opensource/bench-lru/node_modules/lru-native
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/native/src/native.o
In file included from ../src/native.cc:2:
../src/LRUCache.h:12:10: fatal error: 'tr1/unordered_map' file
      not found
#include <tr1/unordered_map>
         ^
1 error generated.
make: *** [Release/obj.target/native/src/native.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dignifiedquire/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0
```

**Comment by ConAntonakos** [comment]
And also fails on Node 8.
